<?xml version="1.0"?>
<package format="3">
  <name>drone_fleet</name>
  <version>0.0.1</version>
  <description>Virtual drone fleet manager for ROS 2 Jazzy.</description>
  <maintainer email="vidhaan@example.com">Vidhaan Agarwal</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

</package>